version: "3.9"

services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - vaani-net

networks:
  vaani-net:
    external: true
